### ISSUE TITLE
Dns Name didn't work

### ISSUE THREAD

**Issue by addisaden** [addisaden/pingfacts#1]
For example "www.google.com" didn't work.

```
>>> Pingfacts.scan("www.google.com")

IPAddr::InvalidAddressError: invalid address: www.google.com
from /data/data/com.termux/files/usr/lib/ruby/2.7.0/ipaddr.rb:598:in `rescue in initialize'
Caused by IPAddr::InvalidAddressError: invalid address
from /data/data/com.termux/files/usr/lib/ruby/2.7.0/ipaddr.rb:651:in `in6_addr'
```

**Comment by addisaden** [comment]
Fixed this issue
